"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 6.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-kq(fe!0m^hr#+7bz#5k=-@r_v1t9*fd7i3iql+ud11k%t=ci^g'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    # Django REST Framework (DRF) is the toolkit we use to build our Web APIs.
    # Think of DRF as a kitchen equipped with all the specialized tools (like blenders, 
    # mixers, and food processors) that allow us to prepare and serve raw data (JSON) 
    # instead of serving full, visual web pages (HTML).
    'rest_framework',
    
    # 'accounts' is the custom Django app we created to manage everything user-related.
    # Think of it as a specialized department in a business office that handles employee records,
    # badges, and security clearance.
    'accounts',
    
    # 'rest_framework_simplejwt.token_blacklist' is our security revocation registry.
    # Think of it like a "revoked keycards list" at a high-security facility.
    # When a user logs out, their token is thrown into this blacklist database table
    # so that even if a hacker finds and steals that token later, our security system
    # will check the blacklist, recognize it, and block them from entering!
    'rest_framework_simplejwt.token_blacklist',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'


# Custom User Model Registration
# By default, Django creates a standard, basic 'User' table in the database when you start.
# Think of this standard user table like buying a generic, pre-packaged filing cabinet. 
# But in our Authify project, we wanted to swap out that generic cabinet for a customized one 
# that allows email logins (our accounts.User model).
# The AUTH_USER_MODEL setting tells Django: "Hey, do not build the generic user cabinet! 
# Instead, use the custom 'User' blueprint we designed inside our 'accounts' app."
AUTH_USER_MODEL = 'accounts.User'


# Django REST Framework Configuration
# This dictionary contains all overall settings for our API toolkit.
REST_FRAMEWORK = {
    # 'DEFAULT_AUTHENTICATION_CLASSES' is the global checklist of how DRF verifies who a caller is.
    # Think of it like a security gate that requires a specific type of passport.
    # By adding 'rest_framework_simplejwt.authentication.JWTAuthentication', we instruct our API 
    # that any request hitting a protected page must present a valid JSON Web Token (JWT).
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
}


# SimpleJWT Configuration
# This dictionary defines how our JSON Web Token (JWT) passes are issued and validated.
# We set clear expiration boundaries so we can securely test token lifetime and rotation behavior.
from datetime import timedelta
SIMPLE_JWT = {
    # 'ACCESS_TOKEN_LIFETIME' is how long an access pass stays active.
    # Think of it like a visitor badge at a tech office that expires after 15 minutes.
    # Once it expires, the user must present their refresh token to get a brand new badge.
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=15),
    
    # 'REFRESH_TOKEN_LIFETIME' is the life of the master pass.
    # Think of it like a membership card that lasts for 1 day.
    # It cannot be used to read database rooms directly, but it can be swapped for a fresh access badge
    # so users don't have to keep re-typing their password every 15 minutes!
    'REFRESH_TOKEN_LIFETIME': timedelta(days=1),
    
    # 'ROTATE_REFRESH_TOKENS' controls whether to issue a brand new refresh token
    # every time a user requests a new access token. We set this to False for simple behavior,
    # or True if we want maximum rotating security! Let's keep it False for initial simplicity.
    'ROTATE_REFRESH_TOKENS': False,
    
    # 'BLACKLIST_AFTER_ROTATION' ensures that once a refresh token is swapped or rotated,
    # the old refresh token is immediately blacklisted and cannot be reused.
    'BLACKLIST_AFTER_ROTATION': True,
    
    # 'AUTH_HEADER_TYPES' defines the prefix word required in our API request header.
    # For example: 'Authorization: Bearer <your-access-token>'
    # 'Bearer' is the standard web convention—it literally means "the bearer of this token has access".
    'AUTH_HEADER_TYPES': ('Bearer',),
}

